#!/bin/sh
#
# This file is part of the Heresy Plugins
# http://github.com/idlemoor/heresy
#
# Copyright 2017 David Spencer, Baildon, West Yorkshire, U.K.
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#===============================================================================
#
# /usr/sbin/heresy_unattended
# Unattended update for Slackware, using slackpkg and (optionally) slackpkgplus
#
#===============================================================================

H_CONFDIR=${H_CONFDIR:-/etc/slackpkg}
if [ -e "$H_CONFDIR"/heresy.conf ]; then
  . "$H_CONFDIR"/heresy.conf
fi

H_LOGFILE=${H_LOGFILE:-/var/log/slackpkg/unattended.log}
mkdir -p "$(dirname "$H_LOGFILE")"

#-------------------------------------------------------------------------------

#### TODO: refuse to run if kernels not blacklisted!

#-------------------------------------------------------------------------------

if [ "$H_UNATTENDED_ENABLED" = 'yes' ]; then
  postinst='off'
  [ "$H_ETC_ENABLED" = 'yes' ] && postinst='on'
  slackpkg -batch=on update >>"$H_LOGFILE" 2>&1
  slackpkg -batch=on -default_answer=y -postinst=$postinst upgrade-all >>"$H_LOGFILE" 2>&1
fi

#===============================================================================
